export const INVOICE_YAML_SCHEMA = [
  "```yaml",
  "department:",
  "  code: string  # 部门代码",
  "",
  "invoice:",
  "  po_no: string        # 订单号/PO号 - Extract ONLY the numeric part",
  "  invoice_date: string # 发票日期 (YYYY-MM-DD)",
  "  usage: string        # 设备信息 (从\"申请/归口部门需求说明\"字段提取)",
  "",
  "items:",
  "  - name: string                    # 货物描述/品名",
  "    quantity: number                # 数量",
  "    unit: string                    # 单位，必须是以下之一: KG, EA, M",
  "    unit_price_ex_tax: number       # 不含税单价 (从\"备注\"字段提取)",
  "    unit_price_inc_tax: number      # 含税单价 (从\"单价\"字段提取)",
  "    total_amount_inc_tax: number    # 含税总价",
  "    cost: string                    # 采购主账号 (从采购申请单表格的\"采购主帐号\"列获取，空值则继承上一行)",
  "",
  "_extraction_info:",
  "  ocr_issues: list          # OCR识别问题的描述",
  "  uncertain_fields: list    # 不确定的字段列表",
  "  suggestions: list         # 改进建议",
  "  notes: string             # 其他备注信息",
  "  confidence: 0.0           # 解析结果的置信度 (0.0-1.0，供人工审核参考)",
  "```",
].join('\n');
